name: 'reusable workflow'
on:
  push:
  workflow_call:
    inputs:
      name:
        type: string
        default: 'Workflow'
        required: false

jobs:
  print_name:
    name: print name
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: |
          echo "Hello ${NAME:-World}"
        env:
          NAME: ${{ inputs.name }}